apiVersion: v2.edp.epam.com/v1alpha1
kind: CodebaseBranch
metadata:
  name: registry-regulations-codebasebranch
  labels:
    type: registry-codebasebranch
spec:
  branchName: master
  codebaseName: registry-regulations
  fromCommit: ''
  release: false
  version: 0.0.1