kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-system-pods
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: monitoring
        - namespaceSelector:
            matchLabels:
              name: istio-system
        - namespaceSelector:
            matchLabels:
              name: openshift-storage
        - namespaceSelector:
            matchLabels:
              name: openshift-ingress
        - namespaceSelector:
            matchLabels:
              name: redis-operator
        - namespaceSelector:
            matchLabels:
              policy-group.network.openshift.io/host-network: ''
  policyTypes:
    - Ingress
