apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: geo-server-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: geo-server
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: kong
      - namespaceSelector:
          matchLabels:
            name: {{ .Values.namespace }}