helmDefaults:
  wait: true
  timeout: 1800
missingFileHandler: Warn
releases:
- name: gerritaccess
  namespace: control-plane
  chart: gerritaccess
  version: 1.0.0
  labels:
    type: local
  values:
  - values.yaml
  - values.gotmpl
  missingFileHandler: Warn
- name: control-plane-console
  namespace: '{{ env "globalEDPProject" }}'
  chart: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/control-plane-console.git/deploy-templates'
  labels:
    type: remote
    isbranch: false
    path: components/infra/
    repoURL: ssh://jenkins@gerrit.mdtu-ddm-edp-cicd:32114/mdtu-ddm/infrastructure/control-plane-console.git
  version: 1.9.7.5
  values:
  - values.yaml
  - values.gotmpl
  hooks:
  - events:
    - prepare
    command: python3
    args:
    - ../scripts/modify_control_plane_version.py
    - '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/control-plane-console.git/deploy-templates/values.yaml'
  - events:
    - presync
    command: oc
    args:
    - adm
    - policy
    - add-scc-to-user
    - anyuid
    - system:serviceaccount:{{ env "globalEDPProject" }}:control-plane-console
  - events:
    - postuninstall
    command: oc
    args:
    - adm
    - policy
    - remove-scc-from-user
    - anyuid
    - system:serviceaccount:{{ env "globalEDPProject" }}:control-plane-console
- name: ddm-architecture
  namespace: documentation
  chart: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/control-plane/ddm-architecture.git/deploy-templates'
  labels:
    repoURL: ssh://jenkins@gerrit.mdtu-ddm-edp-cicd:32114/mdtu-ddm/general/ddm-architecture.git
    update_scc: false
    type: remote
    path: components/control-plane/
    stream: master
  values:
  - values.yaml
  - values.gotmpl
  version: 1.9.6.800
  hooks:
  - events:
    - presync
    showlogs: true
    command: bash
    args:
    - ../scripts/create_namespace.sh
    - '{{`{{ .Release.Namespace }}`}}'
  - events:
    - presync
    showlogs: true
    command: oc
    args:
    - adm
    - policy
    - add-scc-to-user
    - anyuid
    - -z
    - ddm-architecture
    - -n
    - '{{`{{ .Release.Namespace }}`}}'
  - events:
    - postuninstall
    showlogs: true
    command: oc
    args:
    - adm
    - policy
    - remove-scc-from-user
    - anyuid
    - -z
    - ddm-architecture
    - -n
    - '{{`{{ .Release.Namespace }}`}}'
  - events:
    - presync
    showlogs: true
    command: oc
    args:
    - adm
    - policy
    - add-scc-to-user
    - privileged
    - -z
    - ddm-architecture
    - -n
    - '{{`{{ .Release.Namespace }}`}}'
  - events:
    - postuninstall
    showlogs: true
    command: oc
    args:
    - adm
    - policy
    - remove-scc-from-user
    - privileged
    - -z
    - ddm-architecture
    - -n
    - '{{`{{ .Release.Namespace }}`}}'
  - events:
    - presync
    showlogs: true
    command: oc
    args:
    - adm
    - policy
    - add-role-to-user
    - view
    - -z
    - ddm-architecture
    - -n
    - '{{`{{ .Release.Namespace }}`}}'
  - events:
    - postuninstall
    showlogs: true
    command: oc
    args:
    - adm
    - policy
    - remove-role-from-user
    - view
    - -z
    - ddm-architecture
    - -n
    - '{{`{{ .Release.Namespace }}`}}'
helmfiles:
- path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/catalog-source.git/deploy-templates/helmfile.yaml'
- path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/storage.git/deploy-templates/helmfile.yaml'
- path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/monitoring.git/deploy-templates/helmfile.yaml'
- path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/logging.git/deploy-templates/helmfile.yaml'
- path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/service-mesh.git/deploy-templates/helmfile.yaml'
- path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/backup-management.git/deploy-templates/helmfile.yaml'
- path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/control-plane-nexus.git/deploy-templates/helmfile.yaml'
- path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/user-management.git/deploy-templates/helmfile.yaml'
- path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/external-integration-mocks.git/deploy-templates/helmfile.yaml'
- path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/cluster-kafka-operator.git/deploy-templates/helmfile.yaml'
- path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/smtp-server.git/deploy-templates/helmfile.yaml'
- path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/redis-operator.git/deploy-templates/helmfile.yaml'
- path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/postgres-operator.git/deploy-templates/helmfile.yaml'
environments:
  default:
    missingFileHandler: Warn
    values:
    - values.yaml
    - values.gotmpl
  mock:
    missingFileHandler: Warn
    values: []
