helmDefaults:
  wait: true
  timeout: 1800

missingFileHandler: Warn

helmfiles:
  - path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/catalog-source.git/deploy-templates/helmfile.yaml'
  - path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/storage.git/deploy-templates/helmfile.yaml'
  - path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/monitoring.git/deploy-templates/helmfile.yaml'
  - path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/logging.git/deploy-templates/helmfile.yaml'
  - path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/service-mesh.git/deploy-templates/helmfile.yaml'
  - path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/velero.git/deploy-templates/helmfile.yaml'
  - path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/components/infra/control-plane-nexus.git/deploy-templates/helmfile.yaml'
  - path: '{{ env "CUSTOM_BASEDIR" | default "/opt" }}/repositories/user-management.git/deploy-templates/helmfile.yaml'

environments:
  default:
    missingFileHandler: Warn
    values:
      - values.yaml
      - values.gotmpl
      - ../properties/catalog-source_values.yaml
      - ../properties/catalog-source_values.gotmpl
      - ../properties/control-plane-nexus_values.yaml
      - ../properties/control-plane-nexus_values.gotmpl
      - ../properties/logging_values.yaml
      - ../properties/logging_values.gotmpl
      - ../properties/monitoring_values.yaml
      - ../properties/monitoring_values.gotmpl
      - ../properties/service-mesh_values.yaml
      - ../properties/service-mesh_values.gotmpl
      - ../properties/storage_values.yaml
      - ../properties/storage_values.gotmpl
      - ../properties/user-management_values.yaml
      - ../properties/user-management_values.gotmpl
      - ../properties/velero_values.yaml
      - ../properties/velero_values.gotmpl

