apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bp-webservice-gateway-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: bp-webservice-gateway
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kong
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
