apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: excerpt-service-api-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: excerpt-service-api
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: bpms
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kong
        - podSelector:
            matchLabels:
              name: history-excerptor-job
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
