apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: user-settings-service-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: user-settings-service-api
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: bpms
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kong
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ddm-notification-service              
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
