kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cp-registry-admin-{{ .Release.Namespace }}
  namespace: {{ .Values.edpProject }}
rules:
  - verbs:
      - list
    apiGroups:
      - '*'
    resources:
      - codebases
      - codebasebranches
  - verbs:
      - create
    apiGroups:
      - '*'
    resources:
      - JenkinsJobRun
  - verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
    apiGroups:
      - '*'
    resources:
      - codebases
      - codebasebranches
    resourceNames:
      - {{ .Release.Namespace }}
  - apiGroups:
      - '*'
    verbs:
      - create
    resources:
      - secrets
    resourceNames:
      - system-digital-sign-{{ .Release.Namespace }}-key
      - system-digital-sign-{{ .Release.Namespace }}-ca
