apiVersion: v2.edp.epam.com/v1
kind: JenkinsAuthorizationRoleMapping
metadata:
  name: cp-registry-admin-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  roleType: "globalRoles"
  roles:
    - admin
  group: cp-registry-admin-{{ .Release.Namespace }}