kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cp-registry-admin-{{ .Release.Namespace }}-namespace
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - '*'
    resources:
      - '*'
