apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: s3-virtual-service
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - s3.openshift-storage.svc
  http:
    - retries:
        attempts: 3
        retryOn: '504,gateway-error,connect-failure,refused-stream,5xx'
      route:
        - destination:
            host: s3.openshift-storage.svc
      timeout: 10s