apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  namespace: {{ .Values.namespace }}
spec:
  egress:
    - hosts:
        - ./*
        - istio-system/*
        - default/*
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY