{{- if and .Values.griada.enabled .Values.griada.url }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: griada
  namespace: {{ .Values.namespace }}
spec:
  exportTo:
    - "."
  hosts:
    {{- if .Values.griada.url }}
    - {{ .Values.griada.url }}
    {{- else }}
    - griada.{{ .Values.dnsWildcard }}
    {{- end }}
  location: MESH_EXTERNAL
  ports:
    - name: port1
      number: 3011
      protocol: TCP
    - name: port2
      number: 3012
      protocol: TCP
    - name: port3
      number: 3013
      protocol: TCP
    - name: port4
      number: 3014
      protocol: TCP
    - name: port5
      number: 3015
      protocol: TCP
    - name: port6
      number: 3016
      protocol: TCP
  resolution: DNS
{{- end }}
