apiVersion: v1.edp.epam.com/v1alpha1
kind: KeycloakRealmRole
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: cp-registry-admin-{{ .Release.Namespace }}
  namespace: user-management
spec:
  composite: false
  name: cp-registry-admin-{{ .Release.Namespace }}
  realm: openshift
