apiVersion: v1.edp.epam.com/v1alpha1
kind: KeycloakRealmRole
metadata:
  name: cp-registry-admin-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  composite: false
  name: cp-registry-admin-{{ .Release.Namespace }}
  realm: admin
