apiVersion: v1.edp.epam.com/v1alpha1
kind: KeycloakRealmRole
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: realm-admin
  namespace: {{ .Release.Namespace }}
spec:
  composite: false
  name: realm-admin
  realm: admin
