apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: artifactory
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - artifactory.control-plane-nexus
  exportTo:
    - "."
  ports:
    - name: http
      number: 80
      protocol: HTTP
  resolution: DNS
  location: MESH_INTERNAL