apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redash-viewer-adhocworker-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redash-viewer
      app.kubernetes.io/component: adhocworker
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: server
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redash-viewer
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}