kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: registry-rest-api-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: registry-rest-api
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
      from:
        - podSelector:
            matchLabels:
              app: registry-kafka-api
        - podSelector:
            matchLabels:
              app: registry-soap-api
        - podSelector:
            matchLabels:
              app: bpms
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kong
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}