kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cp-registry-admin-{{ .Release.Namespace }}
  namespace: {{ .Values.edpProject }}
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: cp-{{ .Release.Namespace }}-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cp-registry-admin-{{ .Release.Namespace }}