kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: default-network-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: monitoring
        - namespaceSelector:
            matchLabels:
              name: istio-system
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
  policyTypes:
    - Ingress
