kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: platform-gateway-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: platform-gateway
  ingress:
    - from:
        - namespaceSelector: {}