apiVersion: v2.edp.epam.com/v1alpha1
kind: Codebase
metadata:
  name: history-excerptor
  labels:
    recreateByCleanup: "true"
spec:
  commitMessagePattern: null
  jenkinsSlave: dataplatform-jenkins-agent
  gitUrlPath: null
  defaultBranch: master
  branchToCopyInDefaultBranch: {{ .Values.codebases.registryRegulations.historyExcerptorRepoVersion }}
  buildTool: none
  perf: null
  versioning:
    startFrom: 0.0.1
    type: edp
  jobProvisioning: registry
  repository:
    url: {{ .Values.codebases.registryRegulations.historyExcerptorUrl }}
  emptyProject: false
  lang: groovy-pipeline
  deploymentScript: ''
  strategy: clone
  jiraIssueMetadataPayload: null
  gitServer: gerrit
  testReportFramework: null
  ticketNamePattern: null
  type: library
  description: null
  framework: null
  ciTool: Jenkins

