kind: DaemonSet
apiVersion: apps/v1
metadata:
  annotations:
    "helm.sh/hook": post-install
    deprecated.daemonset.template.generation: '2'
    openshift.io/scc: node-exporter
  name: docker-registry-dns-fixer-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: docker-registry-dns-fixer-{{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: docker-registry-dns-fixer-{{ .Release.Namespace }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: docker-registry-dns-fixer-{{ .Release.Namespace }}
      annotations:
        sheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: docker-registry-dns
          command:
            - /bin/sh
            - '-c'
            - |
              sleep 15 && while true;
              do
              SVC_IP=$(oc get -n {{ .Values.globalNexusNamespace }} svc/docker-registry | tail -1 | awk {'print $3'})
              DOCKER_HOST="docker-registry.{{ .Values.globalNexusNamespace }}.svc docker-registry.{{ .Values.globalNexusNamespace }}.svc.cluster.local"
              if grep -q "${DOCKER_HOST}" "/host/etc/hosts"; then
              sed -i -r "s#.*(${DOCKER_HOST})#${SVC_IP} \1#g" /host/etc/hosts
              echo "Docker-registry (${DOCKER_HOST}) has IP: ${SVC_IP} "
              else
              echo "can't find docker-registry record in /host/etc/hosts, docker-registry record will be added"
              echo "$SVC_IP ${DOCKER_HOST}" >> /host/etc/hosts
              echo "Docker-registry service (${DOCKER_HOST}) added with IP: ${SVC_IP}"
                fi
              sleep 30;
              done
          securityContext:
            privileged: true
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: etc
              mountPath: /host/etc
          terminationMessagePolicy: File
          image: 'openshift/origin-cli'
      serviceAccountName: dnslookup
      volumes:
        - name: etc
          hostPath:
            path: /etc
            type: Directory
      dnsPolicy: ClusterFirst
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoSchedule
        - key: node/{{ .Release.Namespace }}
          operator: Exists
          effect: NoSchedule
        - key: node/{{ .Release.Namespace }}
          operator: Exists
          effect: NoExecute
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dnslookup
  namespace: {{ .Release.Namespace }}

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dnslookup
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: dnslookup
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: openshift-config
  name: role-configmap-creation
rules:
  - apiGroups: [""]
    resources: ["configmap"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-configmap-creation-binding
  namespace: openshift-config
subjects:
  - kind: ServiceAccount
    name: nexus
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: role-configmap-creation
  apiGroup: rbac.authorization.k8s.io
