apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: istio-ingressgateway-{{ .Values.stageName }}
  servers:
    - port:
        number: 80
        name: http2
        protocol: HTTP
      hosts:
        - {{ include "citizen-portal.url" . }}
        - {{ include "officer-portal.url" . }}
        - admin-portal-{{ .Values.stageName }}.{{ .Values.dnsWildcard }}
        - external-service-api-{{ .Values.stageName }}.{{ .Values.dnsWildcard }}
        - admin-tools-{{ .Values.stageName }}.{{ .Values.dnsWildcard }}
