apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bpms-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: bpms
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: user-task-management
        - podSelector:
            matchLabels:
              app: user-process-management
        - podSelector:
            matchLabels:
              app: digital-document-service
        - podSelector:
            matchLabels:
              app: bp-webservice-gateway
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}