apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: citus-rep-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: citus-master-rep
  ingress:
    - from:
        - podSelector:
            matchLabels:
              job-name: run-db-scripts-job
        - podSelector:
            matchLabels:
              name: history-excerptor-job
        - podSelector:
            matchLabels:
              app: citus-workers-rep
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redash-admin
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redash-viewer
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
      ports:
        - protocol: TCP
          port: 5432