kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: form-schema-provider-policy
spec:
  podSelector:
    matchLabels:
      app: form-schema-provider
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: form-submission-validation
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: kong
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
  policyTypes:
    - Ingress
