apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: report-exporter-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: report-exporter
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kong-admin-tools
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
