nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/admin-portal-master:1.5.0-SNAPSHOT.34
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/admin-portal-master:1.5.0-SNAPSHOT.81
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/bp-admin-portal-master:1.5.0-SNAPSHOT.27
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/bp-admin-portal-master:1.5.0-SNAPSHOT.67
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/bp-webservice-gateway-master:1.5.0-SNAPSHOT.27
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/bp-webservice-gateway-master:1.5.0-SNAPSHOT.60
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/bpms-master:1.5.0-SNAPSHOT.71
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/bpms-master:1.5.0-SNAPSHOT.153
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/bpms-mdtuddm-10751:1.5.0-MDTUDDM-10751-SNAPSHOT.6
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/citizen-portal-master:1.5.0-SNAPSHOT.34
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/citizen-portal-master:1.5.0-SNAPSHOT.86
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/citusdata/citus:10.0.2
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/citus-master:1.5.0-SNAPSHOT.36
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/citus-master:1.5.0-SNAPSHOT.82
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/citus-master:1.5.0-SNAPSHOT.42
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/epamedp/codebase-operator:2.8.1
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/confluentinc/cp-schema-registry:6.1.1
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/dataplatform-jenkins-agent-master:1.5.0-SNAPSHOT.86
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/digital-document-service-master:1.5.0-SNAPSHOT.24
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/digital-document-service-master:1.5.0-SNAPSHOT.63
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/digital-signature-ops-master:1.5.0-SNAPSHOT.28
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/digital-signature-ops-master:1.5.0-SNAPSHOT.62
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/epamedp/edp-jenkins:2.7.0
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/excerpt-service-api-master:1.5.0-SNAPSHOT.30
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/excerpt-service-api-master:1.5.0-SNAPSHOT.68
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/excerpt-worker-master:1.5.0-SNAPSHOT.29
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/excerpt-worker-master:1.5.0-SNAPSHOT.66
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/form-management-master:1.5.0-SNAPSHOT.35
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/form-management-master:1.5.0-SNAPSHOT.78
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/openfrontier/gerrit:3.3.2
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/epamedp/gerrit-operator:2.8.10
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/epamedp/gerrit-operator:2.8.0-FEATURE-SNAPSHOT.3
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/history-excerptor-master:1.5.0-SNAPSHOT.36
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/epamedp/jenkins-operator:2.9.10
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/epamedp/jenkins-operator:2.9.0-SNAPSHOT.18
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/obsidiandynamics/kafdrop:latest
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/kafka-api-core-base-image-master:1.5.0-SNAPSHOT.41
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/kafka-connect-image-master:1.4.0-SNAPSHOT.26
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/kafka-connect-image-master:1.3.0-SNAPSHOT.5
keycloak-master:1.3.0-SNAPSHOT.11
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/keycloak/keycloak-gatekeeper:10.0.0
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/epamedp/keycloak-operator:1.10.0-SNAPSHOT.28
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/epamedp/keycloak-operator:1.10.0-SNAPSHOT.18
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/kong-master:1.5.0-SNAPSHOT.14
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/model-core-base-image-master:1.4.0-SNAPSHOT.1
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mongo:4.1
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/bitnami/mongodb-exporter:0.11.2-debian-10-r281
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/epamedp/nexus-operator:2.8.0-SNAPSHOT.13
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/epamedp/nexus-operator:2.8.10
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/sonatype/nexus3:3.30.0
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/officer-portal-master:1.5.0-SNAPSHOT.37
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/officer-portal-master:1.5.0-SNAPSHOT.91
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/strimzi/operator:0.20.1
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/strimzi/operator:0.21.1
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/wrouesnel/postgres_exporter:latest
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/bitnami/postgresql:9.6.17-debian-10-r3
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/process-history-service-api-master:1.5.0-SNAPSHOT.6
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/process-history-service-persistence-master:1.5.0-SNAPSHOT.5
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/redash-chart-master:1.5.0-SNAPSHOT.29
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/redash-chart-master:1.5.0-SNAPSHOT.65
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/masahata/redash-exporter
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/bitnami/redis:6.0.8-debian-10-r0
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/report-exporter-master:1.5.0-SNAPSHOT.14
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/report-exporter-master:1.5.0-SNAPSHOT.51
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/report-publisher-master:1.5.0-SNAPSHOT.24
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/report-publisher-master:1.5.0-SNAPSHOT.10
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/rest-api-core-base-image-master:1.5.0-SNAPSHOT.46
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/soap-api-core-base-image-master:1.5.0-SNAPSHOT.32
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/user-process-management-master:1.5.0-SNAPSHOT.38
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/user-process-management-master:1.5.0-SNAPSHOT.74
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/user-settings-service-api-master:1.5.0-SNAPSHOT.21
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/user-settings-service-api-master:1.5.0-SNAPSHOT.52
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/user-settings-service-persistence-master:1.5.0-SNAPSHOT.19
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/user-settings-service-persistence-master:1.5.0-SNAPSHOT.54
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/user-task-management-master:1.5.0-SNAPSHOT.40
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/user-task-management-master:1.5.0-SNAPSHOT.92