nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/admin-portal-release-1-4:1.4.0-RC.14
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/bp-admin-portal-release-1-4:1.4.0-RC.43
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/bp-webservice-gateway-release-1-4:1.4.0-RC.47
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/bpms-release-1-4:1.4.0-RC.57
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/citizen-portal-release-1-4:1.4.0-RC.18
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/citusdata/citus:10.0.2
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/citus-release-1-4:1.4.0-RC.43
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/epamedp/codebase-operator:2.8.1
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/confluentinc/cp-schema-registry:6.1.1
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/dataplatform-jenkins-agent-release-1-4:1.4.0-RC.54
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/digital-document-service-release-1-4:1.4.0-RC.46
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/digital-signature-ops-release-1-4:1.4.2-RC.49
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/epamedp/edp-jenkins:2.7.0
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/excerpt-service-api-release-1-4:1.4.0-RC.45
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/excerpt-worker-release-1-4:1.4.0-RC.46
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/form-management-release-1-4:1.4.0-RC.17
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/epamedp/gerrit-operator:2.8.10
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/history-excerptor-release-1-4:1.4.0-RC.3
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/epamedp/jenkins-operator:2.9.10
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/obsidiandynamics/kafdrop:latest
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/kafka-api-core-base-image-release-1-4:1.4.0-RC.43
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/kafka-connect-image-release-1-3:1.3.0-RC.1
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/epamedp/keycloak-operator:1.10.11
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/kong-release-1-4:1.4.0-RC.5
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/model-core-base-image-release-1-3:1.3.0-RC.2
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mongo:4.1
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/epamedp/nexus-operator:2.8.10
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/officer-portal-release-1-4:1.4.0-RC.34
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/wrouesnel/postgres_exporter:latest
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/bitnami/postgresql:9.6.17-debian-10-r3
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/redash-chart-release-1-4:1.4.0-RC.14
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/masahata/redash-exporter
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/bitnami/redis:6.0.8-debian-10-r0
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/report-exporter-release-1-4:1.4.0-RC.42
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/report-publisher-release-1-4:1.4.0-RC.10
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/rest-api-core-base-image-release-1-4:1.4.0-RC.43
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/soap-api-core-base-image-release-1-4:1.4.0-RC.35
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/user-process-management-release-1-4:1.4.0-RC.49
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/user-settings-service-api-release-1-4:1.4.0-RC.41
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/user-settings-service-persistence-release-1-4:1.4.0-RC.39
nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/user-task-management-release-1-4:1.4.0-RC.49