dataplatform-jenkins-agent-release-1-3:1.3.0-RC.10
kafka-api-core-base-image-release-1-3:1.3.0-RC.6
kafka-connect-image-release-1-2:1.2.0-RC.1
keycloak-release-1-3:1.3.0-RC.3
model-core-base-image-release-1-3:1.3.0-RC.2
rest-api-core-base-image-release-1-3:1.3.0-RC.4
soap-api-core-base-image-release-1-3:1.3.0-RC.2