apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: keycloak-groupsync-{{ .Release.Namespace }}
  namespace: group-sync-operator
spec:
  providers:
    - keycloak:
        credentialsSecret:
          name: keycloak-user-management
          namespace: group-sync-operator
        loginRealm: master
        realm: openshift
        groups:
          - cp-registry-admin-{{ .Release.Namespace }}
        scope: sub
        url: '{{ .Values.keycloak.url }}'
      name: keycloak
  schedule: '*/5 * * * *'
