apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kong-admin-tools-virtual-service
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - admin-tools-{{ .Values.stageName }}.{{ .Values.dnsWildcard }}
  gateways:
    - gateway
  http:
    - route:
        - destination:
            host: kong-admin-tools-kong-admin-tools-proxy
            subset: main
          weight: 100
          headers:
            response:
              remove:
                - x-envoy-upstream-service-time
                - x-kong-response-latency
                - x-envoy-decorator-operation
                - Server
