{{ $secret := (lookup "v1" "Secret" "user-management" "keycloak-client.openshift.secret").data }}

---

{{ if not $secret }}
kind: Secret
apiVersion: v1
metadata:
  name: "keycloak-client.openshift.secret"
  namespace: user-management
data:
  clientSecret: {{ b64enc (randAlphaNum 16) }}
type: Opaque
{{ end }}

---

apiVersion: v1.edp.epam.com/v1alpha1
kind: KeycloakRealmIdentityProvider
metadata:
  name: openshift-sso
  annotations:
    helm.sh/resource-policy: keep
spec:
  realm: master
  alias: openshift-sso
  authenticateByDefault: false
  enabled: true
  firstBrokerLoginFlowAlias: "first broker login"
  providerId: keycloak-oidc
  displayName: "openshift-sso"
  config:
    clientId: "openshift"
    clientSecret: "{{ if $secret }}{{ $secret.clientSecret }}{{ else }}{{ b64enc $oauthclientSecret }}{{ end }}"
    hideOnLoginPage: "false"
    syncMode: "FORCE"
    userInfoUrl: "{{ .Values.keycloak.url }}/auth/realms/openshift/protocol/openid-connect/userinfo"
    tokenUrl: "{{ .Values.keycloak.url }}/auth/realms/openshift/protocol/openid-connect/token"
    authorizationUrl: "{{ .Values.keycloak.url }}/auth/realms/openshift/protocol/openid-connect/auth"
    logoutUrl: "{{ .Values.keycloak.url }}/auth/realms/openshift/protocol/openid-connect/logout"
    clientAuthMethod: "client_secret_post"
  mappers: []