apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: digital-document-service-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: digital-document-service
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kong
        - podSelector:
            matchLabels:
              jenkins: slave
        - podSelector:
            matchLabels:
              app: bpms
        - podSelector:
            matchLabels:
              app: business-process-administration-portal
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}