kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: form-submission-validation-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: form-submission-validation
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: digital-document-service
        - podSelector:
            matchLabels:
              app: user-task-management
        - podSelector:
            matchLabels:
              app: user-process-management
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
  policyTypes:
    - Ingress
