kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: kafka-connect-cluster-connect-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      strimzi.io/cluster: kafka-connect-cluster
      strimzi.io/kind: KafkaConnect
      strimzi.io/name: kafka-connect-cluster-connect
  ingress:
    - ports:
        - protocol: TCP
          port: 8083
      from:
        - podSelector:
            matchLabels:
              strimzi.io/cluster: kafka-connect-cluster
              strimzi.io/kind: KafkaConnect
              strimzi.io/name: kafka-connect-cluster-connect
        - podSelector:
            matchLabels:
              strimzi.io/kind: cluster-operator
          namespaceSelector: {}
