apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: language-server-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: ddm-language-server
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kong-admin-tools
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
