apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nexus-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: nexus
  ingress:
    - from:
        - podSelector: {}
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}