kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: platform-gateway-bp-webservice-gateway
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: bp-webservice-gateway
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: platform-gateway
        - namespaceSelector: {}