apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redash-admin-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redash-admin
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: redash-exporter
        - podSelector:
            matchLabels:
              app: report-exporter
        - podSelector:
            matchLabels:
              app: jenkins
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kong-admin-tools
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}