apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redash-viewer-postgresql-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: postgresql-viewer
      release: redash-viewer
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: adhocworker
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redash-viewer
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: scheduledworker
        - podSelector:
            matchLabels:
              job-name: migrate-redash-script-one-time-viewer
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
      ports:
        - protocol: TCP
          port: 5432