apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: registry-regulation-management-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: registry-regulation-management
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kong
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kong-admin-tools
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
