kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: registry-rest-api-ext-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: registry-rest-api-ext
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
      from:
        - podSelector:
            matchLabels:
              app: platform-gateway
        - namespaceSelector: {}