kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ddm-notification-service-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: ddm-notification-service
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kong
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}