apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redash-viewer-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redash-viewer
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: redash-exporter
        - podSelector:
            matchLabels:
              app: jenkins
        - podSelector:
            matchLabels:
              job-name: create-dashboard-job
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kong
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}