apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmRole
metadata:
  name: cp-registry-admin-{{ .Release.Namespace }}
  namespace: user-management
spec:
  composite: false
  name: cp-registry-admin-{{ .Release.Namespace }}
  realm: openshift
