apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-jenkins-slaves
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              jenkins: slave
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.globalEDPProject }}
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}