apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: common-web-app-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: common-web-app
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kong
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kong-admin-tools
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
