apiVersion: v1
kind: Secret
metadata:
  name: trembita-registries-secrets
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  trembita.registries.edr-registry.auth.token: {{ "token" | b64enc }}