apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jenkins-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: jenkins
  ingress:
    - from:
        - podSelector:
            matchLabels:
              name: jenkins-operator
        - podSelector:
            matchLabels:
              name: codebase-operator
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}