kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: kafka-cluster-policy-kafka
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      strimzi.io/name: kafka-cluster-kafka
  ingress:
    - ports:
        - protocol: TCP
          port: 9090
      from:
        - podSelector:
            matchLabels:
              strimzi.io/name: kafka-cluster-kafka
    - ports:
        - protocol: TCP
          port: 9091
        - protocol: TCP
          port: 9092
        - protocol: TCP
          port: 9093  
        - protocol: TCP
          port: 9404                             
      from:
        - podSelector:
            matchLabels:
              strimzi.io/kind: cluster-operator
          namespaceSelector: {}
        - podSelector:
            matchLabels:
              strimzi.io/name: kafka-cluster-kafka
        - podSelector:
            matchLabels:
              strimzi.io/name: kafka-cluster-entity-operator
        - podSelector:
            matchLabels:
              strimzi.io/name: kafka-cluster-kafka-exporter
        - podSelector:
            matchLabels:
              strimzi.io/name: kafka-cluster-cruise-control
