apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redash-admin-adhocworker-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redash-admin
      app.kubernetes.io/component: adhocworker
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redash-admin
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: server
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}