kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: kafka-cluster-policy-zookeeper
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      strimzi.io/name: kafka-cluster-zookeeper
  ingress:
    - ports:
        - protocol: TCP
          port: 2888
        - protocol: TCP
          port: 3888
      from:
        - podSelector:
            matchLabels:
              strimzi.io/name: kafka-cluster-zookeeper
    - ports:
        - protocol: TCP
          port: 2181
      from:
        - podSelector:
            matchLabels:
              strimzi.io/name: kafka-cluster-kafka
        - podSelector:
            matchLabels:
              strimzi.io/name: kafka-cluster-zookeeper
        - podSelector:
            matchLabels:
              strimzi.io/name: kafka-cluster-entity-operator
        - podSelector:
            matchLabels:
              strimzi.io/kind: cluster-operator
          namespaceSelector: {}
        - podSelector:
            matchLabels:
              strimzi.io/name: kafka-cluster-cruise-control
