apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-connect-cluster-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: kafka-connect
  ingress:
    - from:
        - podSelector:
            matchLabels:
              name: strimzi-cluster-operator
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
