apiVersion: v2.edp.epam.com/v1alpha1
kind: JenkinsAuthorizationRole
metadata:
  name: cp-registry-admin-{{ .Release.Namespace }}
  namespace: {{ .Values.globalEDPProject }}
spec:
  name: cp-registry-admin-{{ .Release.Namespace }}
  roleType: "projectRoles"
  pattern: "^{{ .Release.Namespace }}/*.*"
  permissions:
    - "hudson.model.Item.Read"
    - "hudson.model.Item.Build"

---

apiVersion: v2.edp.epam.com/v1alpha1
kind: JenkinsAuthorizationRole
metadata:
  name: cp-registry-admin-{{ .Release.Namespace }}-global
  namespace: {{ .Values.globalEDPProject }}
spec:
  name: cp-registry-admin-{{ .Release.Namespace }}-global
  roleType: "globalRoles"
  pattern: "*.*"
  permissions:
    - "hudson.model.Hudson.Read"