kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: citus-workers-rep-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: citus-workers-rep
  ingress:
    - ports:
        - protocol: TCP
          port: 5432
      from:
        - podSelector:
            matchLabels:
              app: citus-master-rep
        - podSelector:
            matchLabels:
              job-name: run-db-scripts-job
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
