kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: kafka-schema-registry-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: kafka-schema-registry
  ingress:
    - ports:
        - protocol: TCP
          port: 8081
      from:
        - podSelector:
            matchLabels:
              app: registry-rest-api
        - podSelector:
            matchLabels:
              app: registry-rest-api-ext
        - podSelector:
            matchLabels:
              app: registry-kafka-api
        - podSelector:
            matchLabels:
              app: user-settings-service-api
        - podSelector:
            matchLabels:
              app: process-history-service-api
        - podSelector:
            matchLabels:
              app: process-history-service-persistence
        - podSelector:
            matchLabels:
              app: excerpt-service-api
        - podSelector:
            matchLabels:
              app: excerpt-worker
        - podSelector:
            matchLabels:
              app: excerpt-worker-docx
        - podSelector:
            matchLabels:
              app: excerpt-worker-csv
        - podSelector:
            matchLabels:
              app: user-publisher
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kafka-connect
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: ddm-notification-service
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
