apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gerrit-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: gerrit
  ingress:
    - from:
        - podSelector:
            matchLabels:
              name: gerrit-operator
        - podSelector:
            matchLabels:
              app: jenkins
        - podSelector:
            matchLabels:
              name: codebase-operator
        - podSelector:
            matchLabels:
              app: registry-regulation-management
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kong-admin-tools
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
