apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jenkins-control-plane-ns-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: jenkins
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: jenkins
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.globalEDPProject }}