kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: platform-gateway-policy-kong
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: platform-gateway
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
      from:
        - podSelector:
            matchLabels:
              app: bpms
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kong
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}