apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redash-admin-postgresql-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: postgresql-admin
      release: redash-admin
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redash-admin
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: adhocworker
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: scheduledworker
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.namespace }}
      ports:
        - protocol: TCP
          port: 5432