apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gerrit-operator-admin-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gerrit-operator.metaLabels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.operator.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
