apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: gerrit
    {{- include "gerrit-operator.metaLabels" . | nindent 4 }}
  name: gerrit
spec:
  host: {{ template "gerrit.hostname" . }}
  path: /
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: gerrit
    weight: 100
  wildcardPolicy: None
status:
  ingress: []