{{- if .Values.keycloakIntegration.enabled -}}
{{- if not .Values.keycloakIntegration.client.public -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.keycloakIntegration.client.secretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloakIntegration.client.secretName }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
  {{- include "gerrit-operator.metaLabels" . | nindent 4 }}
type: Opaque
  {{- if $secret }}
data:
  # Gerrit operator looking for client_secret key, but keycloak supports only clientSecret key name
  # so we have to temporary double it
  clientSecret: {{ $secret.data.clientSecret }}
  client_secret: {{ $secret.data.clientSecret }}
  {{- else }}
stringData:
  {{- $clientSecret := uuidv4 | quote }}
  clientSecret: {{ $clientSecret }}
  client_secret: {{ $clientSecret }}
{{- end -}}
{{- end -}}
{{- end -}}