apiVersion: v1
kind: Service
metadata:
  name: gerrit
  labels:
    app: gerrit
  {{- include "gerrit-operator.metaLabels" . | nindent 4 }}
spec:
  ports:
    - name: ui
      protocol: TCP
      port: {{ .Values.gerrit.port }}
      targetPort: {{ .Values.gerrit.port }}
    - name: ssh
      protocol: TCP
      port: {{ .Values.gerrit.sshPort }}
      targetPort: {{ .Values.gerrit.sshPort }}
      nodePort: {{ .Values.gerrit.sshPort }}
  selector:
    app: gerrit
  type: NodePort
