apiVersion: v2.edp.epam.com/v1alpha1
kind: GitServer
metadata:
  name: gerrit
  labels:
  {{- include "gerrit-operator.metaLabels" . | nindent 4 }}
spec:
  createCodeReviewPipeline: false
  gitHost: gerrit
  gitUser: jenkins
  httpsPort: 8080
  nameSshKeySecret: gerrit-ciuser-sshkey
  sshPort: {{ .Values.gerrit.sshPort }}