# helm values
---
griada:
  enabled: false
  # 10.0.0.1
  ip: ""
  # 3080
  port: ""
  # Griada url by default is: griada.<clusterDnsWildcard>
  # example.com
  url: ""

nontrembita-external-registration: []

# You may enable a Kong rate limiting plugin for portals
# Also you may configure this plugin by changing the default variables below
kongPluginsConfig:
  rateLimitingPluginEnable: false
  pluginsRateLimitByHeaderRequestsPerSecond: 10
  pluginsRateLimitByHeaderRequestsPerHour: 10000
  pluginsRateLimitByHeaderPolicy: "local"
  pluginsRateLimitByHeaderFaultTolerant: "true"
  pluginsRateLimitByHeaderHideClientHeaders: "false"
  pluginsRateLimitByHeaderHeaderName: "token-claim"
  pluginsRateLimitByIpRequestsPerSecond: 10
  pluginsRateLimitByIpRequestsPerHour: 10000
  pluginsRateLimitByIpPolicy: "local"
  pluginsRateLimitByIpFaultTolerant: "true"
  pluginsRateLimitByIpHideClientHeaders: "false"
  pluginsProxyCacheTtl: 900
  pluginsPrometheusStatusCodeMetrics: true
  pluginsPrometheusLatencyMetrics: true
  pluginsPrometheusBandwidthMetrics: true
  pluginsPrometheusPerConsumerMetrics: true

signWidget:
  url: https://eu.iit.com.ua/sign-widget/v20240301/

# Redash service settings
redash: {}
# customUrl: https://example.com

## Level of logging for the kong and controller. Allowed values are
## trace, debug, info, warn, error, fatal and panic. (default "info")
#env:
#  log_level: info
#ingressController:
#  env:
#    log_level: info
#
## Level of logging for the pg-exporter-chart. Allowed values are
## debug, info, warn, error, fatal. (default "info")
#config:
#  log_level: info
#
## Level of logging for the strimzi-kafka-operator. Allowed values are
## TRACE, DEBUG, INFO, WARN, ERROR. (default "INFO")
#logLevel: INFO
#
## Level of logging for the redash. Allowed values are
## NOTSET, DEBUG, INFO, WARNING, ERROR, CRITICAL. (default "INFO")
#redash:
#  logLevel: INFO
#
## Configures the log verbosity of the Vault injector.
## Supported log levels include: trace, debug, info, warn, error
#injector:
#  logLevel: "info"
## Configure the logging verbosity for the Vault server.
## Supported log levels include: trace, debug, info, warn, error
#server:
#  logLevel: "info"
#
## Level of logging for the Citus. Allowed values are
## debug1, debug2, debug3, debug4, debug5, info, notice, warning
## error, log, fatal, panic. (default "warning")
#citus:
#  pgConfig:
#    logLevel: warning
## Level of logging for the admin/officer/citizen portals. Allowed values are
## emerg, alert, crit, error, warn, notice, info, debug. (default "error")
## It is also possible to turn off the access_log.
#portals:
#  admin:
#    nginx:
#      logLevel: error
#      disableAccessLog: false
#  officer:
#    nginx:
#      logLevel: error
#      disableAccessLog: false
#  citizen:
#    nginx:
#      logLevel: error
#      disableAccessLog: false
global:
  language: ""
  container:
    requestsLimitsEnabled: true
  istio:
    sidecar:
      requestsLimitsEnabled: true
  computeResources:
    instanceCount: 2
    awsInstanceType: "r5.2xlarge"
    awsSpotInstance: false
    awsSpotInstanceMaxPrice: ""
    awsInstanceVolumeType: "gp3"
    instanceVolumeSize: 80
    vSphereInstanceCPUCount: 8
    vSphereInstanceCoresPerCPUCount: 1
    vSphereInstanceRAMSize: 65536
  geoServerEnabled: false
  kafkaOperator:
    replicationFactor: 1
    storage:
      kafka:
        size: 20Gi
      zookeeper:
        size: 5Gi
  whiteListIP:
    adminRoutes: "0.0.0.0/0"
  excludePortals: ['']
  connectSourceList: []
  deploymentMode: development
  region: ua
  bpAdminPortal:
    camunda:
      bpm:
        metrics:
          enabled: true
          scrapeInterval: 60s
  regulationManagement:
    maxCandidateVersions: 10
  crunchyPostgres:
    postgresql:
      parameters:
        max_connections: 200
    storageSize: 10Gi
    backups:
      pgbackrest:
        repos:
          schedules:
            full: "0 1 * * *"
  registry:
    istioIngressGateway:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    geoServer:
      istio:
        sidecar:
          enabled: true
      replicas: 1
    kong:
      istio:
        sidecar:
          enabled: true
      replicas: 1
    kongAdminTools:
      istio:
        sidecar:
          enabled: true
      replicas: 1
    bpms:
      container:
        envVars:
          JAVA_OPTS: "-Xms1536m -Xmx1536m -Duser.timezone=UTC"
      istio:
        sidecar:
          enabled: true
      replicas: 1
    digitalSignatureOps:
      container:
        envVars:
          JAVA_OPTS: "-Xms768m -Xmx768m -Duser.timezone=UTC"
      istio:
        sidecar:
          enabled: true
      replicas: 1
    userTaskManagement:
      container:
        envVars:
          JAVA_OPTS: "-Xms512m -Xmx512m"
      istio:
        sidecar:
          enabled: true
      replicas: 1
    userProcessManagement:
      container:
        envVars:
          JAVA_OPTS: "-Xms512m -Xmx512m"
      istio:
        sidecar:
          enabled: true
      replicas: 1
    digitalDocumentService:
      container:
        envVars:
          JAVA_OPTS: "-Xms512m -Xmx512m"
      istio:
        sidecar:
          enabled: true
      replicas: 1
    restApi:
      container:
        envVars:
          JAVA_OPTS: "-Xms1200m -Xmx1200m -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent"
      datasource:
        maxPoolSize: 10
      istio:
        sidecar:
          enabled: true
      replicas: 1
    kafkaApi:
      container:
        envVars:
          JAVA_OPTS: "-Xms1200m -Xmx1200m -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent"
      datasource:
        maxPoolSize: 10
      istio:
        sidecar:
          enabled: true
      replicas: 1
    soapApi:
      container:
        envVars:
          JAVA_OPTS: "-Xms128m -Xmx128m -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent"
      istio:
        sidecar:
          enabled: true
      replicas: 1
    redis:
      istio:
        sidecar:
          enabled: false
      replicas: 2
    sentinel:
      istio:
        sidecar:
          enabled: true
      replicas: 3
    kafkaClusterKafka:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    kafkaClusterZookeper:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    kafkaConnectClusterConnect:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    kafkaClusterEntityOperator:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    kafkaClusterKafkaExporter:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    kafkaUi:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    wiremock:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    operationalInstance:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    analyticalInstance:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    operationalPool:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    kafkaSchemaRegistry:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    externalSecrets:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    adminPortal:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    citizenPortal:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    officerPortal:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    bpAdminPortal:
      container:
        envVars:
          JAVA_OPTS: "-Xms512m -Xmx512m"
      istio:
        sidecar:
          enabled: false
      replicas: 1
    bpWebserviceGateway:
      container:
        envVars:
          JAVA_OPTS: "-Xms512m -Xmx512m"
      istio:
        sidecar:
          enabled: true
      replicas: 1
    ddmLanguageServer:
      istio:
        sidecar:
          enabled: true
      replicas: 1
    ddmNotificationService:
      istio:
        sidecar:
          enabled: true
      replicas: 1
    excerptServiceApi:
      container:
        envVars:
          JAVA_OPTS: "-Xms330m -Xmx330m -XX:+AlwaysPreTouch -XX:+UseG1GC"
      istio:
        sidecar:
          enabled: true
      replicas: 1
    excerptWorkerCsv:
      container:
        envVars:
          JAVA_OPTS: "-Xms330m -Xmx330m -XX:+AlwaysPreTouch -XX:+UseG1GC"
      istio:
        sidecar:
          enabled: true
      replicas: 1
    excerptWorker:
      container:
        envVars:
          JAVA_OPTS: "-Xms330m -Xmx330m -XX:+AlwaysPreTouch -XX:+UseG1GC"
      istio:
        sidecar:
          enabled: true
      replicas: 1
    excerptWorkerDocx:
      container:
        envVars:
          JAVA_OPTS: "-Xms330m -Xmx330m -XX:+AlwaysPreTouch -XX:+UseG1GC"
      istio:
        sidecar:
          enabled: true
      replicas: 1
    formSchemaProvider:
      istio:
        sidecar:
          enabled: true
      replicas: 1
    formSubmissionValidation:
      istio:
        sidecar:
          enabled: true
      replicas: 1
    gerrit:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    hashicorpVault:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    jenkins:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    nexus:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    pgAdmin:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    platformGateway:
      container:
        envVars:
          JAVA_OPTS: "-Xms330m -Xmx330m -XX:+AlwaysPreTouch -XX:+UseG1GC"
      istio:
        sidecar:
          enabled: true
      replicas: 1
    processHistoryServicePersistence:
      container:
        envVars:
          JAVA_OPTS: "-Xms330m -Xmx330m -XX:+AlwaysPreTouch -XX:+UseG1GC"
      istio:
        sidecar:
          enabled: true
      replicas: 1
    processHistoryServiceApi:
      container:
        envVars:
          JAVA_OPTS: "-Xms330m -Xmx330m -XX:+AlwaysPreTouch -XX:+UseG1GC"
      istio:
        sidecar:
          enabled: true
      replicas: 1
    registryRegulationManagement:
      istio:
        sidecar:
          enabled: true
      replicas: 1
    reloader:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    reportExporter:
      istio:
        sidecar:
          enabled: true
      replicas: 1
    userSettingsServiceApi:
      container:
        envVars:
          JAVA_OPTS: "-Xms330m -Xmx330m -XX:+AlwaysPreTouch -XX:+UseG1GC"
      istio:
        sidecar:
          enabled: true
      replicas: 1
    redashAdmin:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    redashAdminAdhocworker:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    redashAdminRedisMaster:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    redashAdminScheduler:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    redashExporter:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    redashViewer:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    redashViewerAdhocworker:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    redashViewerRedisMaster:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    redashViewerScheduler:
      istio:
        sidecar:
          enabled: false
      replicas: 1

external-systems:
  diia:
    protocol: REST
    type: platform
trembita:
  registries:
    dracs-registry:
      protocol: SOAP
      type: platform
    edr-registry:
      protocol: SOAP
      type: platform
    idp-exchange-service-registry:
      protocol: SOAP
      type: platform
keycloak:
  realms:
    officerPortal:
      browserFlow: dso-officer-auth-flow
      selfRegistration: false
  authFlows:
    officerAuthFlow:
      widgetHeight: 720
  citizenAuthFlow:
    edrCheck: true
    authType: widget
    widget:
      url: https://eu.iit.com.ua/sign-widget/v20240301/
      height: 720
digitalDocuments:
  maxFileSize: 100MB
  maxTotalFileSize: 100MB
portals:
  citizen:
    signWidget:
      url: https://eu.iit.com.ua/sign-widget/v20240301/
      height: 720
      copyFromAuthWidget: true
  officer:
    enableSingleIdentity: false
bpms:
  datasource:
    maxPoolSize: 10
  camunda:
    bpm:
      jobExecution:
        corePoolSize: 3
        maxPoolSize: 10
        maxJobsPerAcquisition: 3
        queueCapacity: 3
      databaseHistoryLevel: ACTIVITY
processHistoryServiceApi:
  datasource:
    maxPoolSize: 10
