# helm values

# You may disable griada instance and set the url
# Griada url by default is: griada.<clusterDnsWildcard>
griada:
  enabled: true
#  url: example.com

# You may enable a Kong rate limiting plugin for portals
# Also you may configure this plugin by changing the default variables below
kongPluginsConfig:
  rateLimitingPluginEnable: false
  pluginsRateLimitByHeaderRequestsPerSecond: 10
  pluginsRateLimitByHeaderRequestsPerHour: 10000
  pluginsRateLimitByHeaderPolicy: "local"
  pluginsRateLimitByHeaderFaultTolerant: "true"
  pluginsRateLimitByHeaderHideClientHeaders: "false"
  pluginsRateLimitByHeaderHeaderName: "token-claim"
  pluginsRateLimitByIpRequestsPerSecond: 10
  pluginsRateLimitByIpRequestsPerHour: 10000
  pluginsRateLimitByIpPolicy: "local"
  pluginsRateLimitByIpFaultTolerant: "true"
  pluginsRateLimitByIpHideClientHeaders: "false"
  pluginsProxyCacheTtl: 900
  pluginsPrometheusStatusCodeMetrics: true
  pluginsPrometheusLatencyMetrics: true
  pluginsPrometheusBandwidthMetrics: true
  pluginsPrometheusPerConsumerMetrics: true

## Level of logging for the kong and controller. Allowed values are
## trace, debug, info, warn, error, fatal and panic. (default "info")
#env:
#  log_level: info
#ingressController:
#  env:
#    log_level: info
#
## Level of logging for the pg-exporter-chart. Allowed values are
## debug, info, warn, error, fatal. (default "info")
#config:
#  log_level: info
#
## Level of logging for the strimzi-kafka-operator. Allowed values are
## TRACE, DEBUG, INFO, WARN, ERROR. (default "INFO")
#logLevel: INFO
#
## Level of logging for the redash. Allowed values are
## NOTSET, DEBUG, INFO, WARNING, ERROR, CRITICAL. (default "INFO")
#redash:
#  logLevel: INFO
#
## Configures the log verbosity of the Vault injector.
## Supported log levels include: trace, debug, info, warn, error
#injector:
#  logLevel: "info"
## Configure the logging verbosity for the Vault server.
## Supported log levels include: trace, debug, info, warn, error
#server:
#  logLevel: "info"
#
## Level of logging for the Citus. Allowed values are
## debug1, debug2, debug3, debug4, debug5, info, notice, warning
## error, log, fatal, panic. (default "warning")
#citus:
#  pgConfig:
#    logLevel: warning
## Level of logging for the admin/officer/citizen portals. Allowed values are
## emerg, alert, crit, error, warn, notice, info, debug. (default "error")
## It is also possible to turn off the access_log.
#portals:
#  admin:
#    nginx:
#      logLevel: error
#      disableAccessLog: false
#  officer:
#    nginx:
#      logLevel: error
#      disableAccessLog: false
#  citizen:
#    nginx:
#      logLevel: error
#      disableAccessLog: false
global:
  whiteListIP:
    adminRoutes: "0.0.0.0/0"
  excludePortals: ['']
  deploymentMode: production
  bpAdminPortal:
    camunda:
      bpm:
        metrics:
          enabled: true
          scrapeInterval: 60s
  regulationManagement:
    maxCandidateVersions: 10
  crunchyPostgres:
    postgresql:
      parameters:
        max_connections: 200
    storageSize: 10Gi
    backups:
      pgbackrest:
        repos:
          schedules:
            full: "0 1 * * *"
  registry:
    kong:
      istio:
        sidecar:
          enabled: true
          resources:
            requests:
              cpu: 600m
              memory: 512Mi
            limits:
              cpu: 600m
              memory: 512Mi
      container:
        resources:
          limits:
            cpu: 300m
            memory: 1Gi
          requests:
            cpu: 300m
            memory: 1Gi
    bpms:
      istio:
        sidecar:
          enabled: true
          resources:
            requests:
              cpu: 350m
              memory: 128Mi
            limits:
              cpu: 350m
              memory: 128Mi
      container:
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 2Gi
        envVars:
          JAVA_OPTS: "-Xms1536m -Xmx1536m -Duser.timezone=UTC"
    digitalSignatureOps:
      istio:
        sidecar:
          enabled: true
          resources:
            requests:
              cpu: 350m
              memory: 128Mi
            limits:
              cpu: 350m
              memory: 128Mi
      container:
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: '1'
            memory: 1Gi
        envVars:
          JAVA_OPTS: "-Xms768m -Xmx768m -Duser.timezone=UTC"
    userTaskManagement:
      istio:
        sidecar:
          enabled: true
          resources:
            requests:
              cpu: 350m
              memory: 128Mi
            limits:
              cpu: 350m
              memory: 128Mi
      container:
        resources:
          limits:
            cpu: 500m
            memory: 768Mi
          requests:
            cpu: 500m
            memory: 768Mi
        envVars:
          JAVA_OPTS: "-Xms512m -Xmx512m"
    userProcessManagement:
      istio:
        sidecar:
          enabled: true
          resources:
            requests:
              cpu: 350m
              memory: 128Mi
            limits:
              cpu: 350m
              memory: 128Mi
      container:
        resources:
          limits:
            cpu: 500m
            memory: 768Mi
          requests:
            cpu: 500m
            memory: 768Mi
        envVars:
          JAVA_OPTS: "-Xms512m -Xmx512m"
    digitalDocumentService:
      istio:
        sidecar:
          enabled: true
          resources:
            requests:
              cpu: 350m
              memory: 128Mi
            limits:
              cpu: 350m
              memory: 128Mi
      container:
        resources:
          limits:
            cpu: 500m
            memory: 768Mi
          requests:
            cpu: 500m
            memory: 768Mi
        envVars:
          JAVA_OPTS: "-Xms512m -Xmx512m"
    restApi:
      istio:
        sidecar:
          enabled: true
          resources:
            requests:
              cpu: 350m
              memory: 128Mi
            limits:
              cpu: 350m
              memory: 128Mi
      container:
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 2Gi
        envVars:
          JAVA_OPTS: "-Xms1200m -Xmx1200m -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent"
    kafkaApi:
      istio:
        sidecar:
          enabled: true
          resources:
            requests:
              cpu: 350m
              memory: 128Mi
            limits:
              cpu: 350m
              memory: 128Mi
      container:
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 2Gi
        envVars:
          JAVA_OPTS: "-Xms1200m -Xmx1200m -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent"
    soapApi:
      istio:
        sidecar:
          enabled: true
          resources:
            requests:
              cpu: 350m
              memory: 128Mi
            limits:
              cpu: 350m
              memory: 128Mi
      container:
        resources:
          limits:
            cpu: 300m
            memory: 600Mi
          requests:
            cpu: 300m
            memory: 600Mi
        envVars:
          JAVA_OPTS: "-Xms128m -Xmx128m -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent"
    redis:
      istio:
        sidecar:
          enabled: false
      container:
        resources:
          limits:
            cpu: '500m'
            memory: 500Mi
          requests:
            cpu: '500m'
            memory: 500Mi
    sentinel:
      istio:
        sidecar:
          enabled: true
          resources:
            requests:
              cpu: 350m
              memory: 128Mi
            limits:
              cpu: 350m
              memory: 128Mi
      container:
        resources:
          limits:
            cpu: 350m
            memory: 128Mi
          requests:
            cpu: 350m
            memory: 128Mi
external-systems:
  diia:
    protocol: REST
    type: platform
trembita:
  registries:
    dracs-registry:
      protocol: SOAP
      type: platform
    edr-registry:
      auth:
        type: AUTH_TOKEN
      client:
        member-class: GOV
        member-code: "43395033"
        subsystem-code: IDGOV_TEST_01
        x-road-instance: SEVDEIR-TEST
      protocol: SOAP
      protocol-version: "4.0"
      service:
        member-class: GOV
        member-code: "00015622"
        subsystem-code: 2_MJU_EDR_prod
        x-road-instance: SEVDEIR-TEST
      type: platform
      user-id: DDM
    idp-exchange-service-registry:
      protocol: SOAP
      type: platform
digitalDocuments:
  maxFileSize: 100MB
  maxTotalFileSize: 100MB
