apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: platform-keycloak
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - platform-keycloak.{{ .Values.dnsWildcard }}
  exportTo:
    - "."
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
  location: MESH_INTERNAL