apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: 'true'
  name: kong-global-file-log
config:
  path: /dev/stdout
plugin: file-log
