{{- if .Values.global.notifications.diia -}}
{{- if .Values.global.notifications.diia.url -}}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ include "notifications.diia.url" . | replace "." "-" }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ include "notifications.diia.url" . }}
  exportTo:
    - "."
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
{{- end -}}
{{- end -}}